# Generated by Django 5.1.15 on 2026-05-28 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Procurement Export'), ('utility', 'Utility Portal CSV'), ('travel', 'Corporate Travel Export')], max_length=20)),
                ('source_row_hash', models.CharField(help_text='SHA-256 of raw source row for dedup', max_length=64)),
                ('source_reference', models.CharField(blank=True, help_text='PO number, meter ID, expense ID, etc.', max_length=255)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 — Direct'), ('scope_2', 'Scope 2 — Purchased Energy'), ('scope_3', 'Scope 3 — Value Chain')], max_length=20)),
                ('category', models.CharField(choices=[('fuel', 'Stationary/Mobile Fuel'), ('procurement', 'Purchased Goods'), ('electricity', 'Purchased Electricity'), ('travel_air', 'Business Travel — Air'), ('travel_hotel', 'Business Travel — Hotel'), ('travel_ground', 'Business Travel — Ground')], max_length=30)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('site_code', models.CharField(blank=True, max_length=50)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(help_text='Normalized unit (L, kWh, km, nights, etc.)', max_length=20)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=20)),
                ('emission_factor_ref', models.CharField(blank=True, max_length=100)),
                ('estimated_co2e_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged — Needs Attention'), ('approved', 'Approved'), ('locked', 'Locked for Audit')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('analyst_notes', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(default=dict, help_text='Original parsed row for audit replay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='ingestion.ingestionrun')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('locked', 'Locked'), ('edited', 'Edited by Analyst')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.activityrecord')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.ingestionrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'status'], name='emissions_a_tenant__16bbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'source_type'], name='emissions_a_tenant__3dc982_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'scope'], name='emissions_a_tenant__29576f_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['tenant', 'activity_date'], name='emissions_a_tenant__150537_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_type', 'source_row_hash'), name='unique_activity_per_source_row'),
        ),
    ]
